apiVersion: v1

kind: Service

metadata:
  name: node-service
  namespace: web-app
  labels:
    app: node-service

spec:
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-app
