apiVersion: v1

kind: Service

metadata:
  name: db-svc
  namespace: web-app
  labels:
    app: db-svc

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: database
